import "./globals.css";
export const metadata = {
  title: "Explorem",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html>
      <body className="bg-[#f5f5f5] ">
        <main>{children}</main>
      </body>
    </html>
  );
}
