import { NextIntlClientProvider, useMessages } from "next-intl";
import Footer from "./components/footer/Footer";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { unstable_setRequestLocale } from "next-intl/server";
const locales = ["en", "de", "ar"];
export const metadata = {
  title: "Explorem",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}
export default function RootLayout({ children, params: { locale } }) {
  unstable_setRequestLocale(locale);
  const messages = useMessages();
  return (
    <main className="">
      <NextIntlClientProvider locale={locale} messages={messages}>
        <div className="flex flex-col justify-between  h-screen">
          <Navbar locale={locale} />
          <div className=" mb-auto bg-[#f5f5f5]">{children}</div>
          <Footer />
        </div>
      </NextIntlClientProvider>
    </main>
  );
}
