import { NextIntlClientProvider, useMessages } from "next-intl";
import Footer from "./components/footer/Footer";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "Explorem",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body className="bg-[#f5f5f5]">
        <NextIntlClientProvider
          
          locale={locale}
          messages={messages}
        >
          <div className="flex flex-col justify-between  h-screen">
            <Navbar locale={locale} />
            <div className="  mb-auto bg-[#f5f5f5]">
              {children}
            </div>
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
